apiVersion: v1
kind: Pod
metadata:
  name: accesshostpod-ubuntu
spec:
  containers:
  - image: public.ecr.aws/ubuntu/ubuntu:18.04_stable
    name: ubuntu
    command:
    - sleep
    - "3600"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      # directory location on host
      path: /