apiVersion: v1
kind: Pod
metadata:
  name: accesshostpod-centos
spec:
  containers:
  - image: public.ecr.aws/docker/library/centos:centos7.9.2009
    name: centos
    command:
    - sleep
    - "3600"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      # directory location on host
      path: /