apiVersion: v1
kind: Pod
metadata:
  name: accesshostpod-amazon-linux
spec:
  containers:
  - image: public.ecr.aws/amazonlinux/amazonlinux:2022
    name: amznlinux
    command:
    - sleep
    - "3600"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      # directory location on host
      path: /